### ISSUE TITLE
config ファイルの中身が invalid な形式だったときは例外を投げて止まってほしい

### ISSUE THREAD

**Issue by sunaot** [bm-sms/keg#14]
config ファイルのフォーマットによるかもしれないが、parse error 相当のときの処理が考慮されててほしい。

**Comment by yuta-muramoto** [comment]
とりあえずconfigのフォーマットを下のようなyaml形式で書いてみます。
```yaml
database: 'oosaka'
```
config.ymlの中身が空だった時はparse errorを出力するようにしてみます。
