### ISSUE TITLE
もっと OOP してみる

### ISSUE THREAD

**Issue by sunaot** [bm-sms/keg#16]
練習も兼ねて。

* `Keg::Database.new` ができるようになったら、コンストラクタにはなにを渡すといい？
* `Keg::Configuration.new` ができるようになったら、コンストラクタにはなにを渡すといい？

ちなみに、Formatter は

* Formatter は module -> class にしつつ、クラスメソッドを利用する今の実装をほとんど踏襲する
* Formatter から呼ばれる Formatter::Json や Formatter::Yaml はインスタンスを生成して返すように設計を変える

今は Module クラスのインスタンスを formatter 変数に入れて Module クラスのクラスメソッドを呼ばせるというトリッキーな設計になってるので、より一般的なインスタンスを使ったポリモーフィズムにしてみましょう。

**Comment by yuta-muramoto** [comment]
`Keg::Database`も`Keg::Configuration`のコンストラクタには`.keg`の場所を渡すことになると思います。ENVの呼び出しをCLIで止めるという意味と、読み出し場所は必須の情報だと考えたからです。

**Comment by sunaot** [comment]
よさそうな気がします！
